Command: /Users/tanwat/.espressif/python_env/idf6.0_py3.13_env/bin/python /Users/tanwat/esp-idf/tools/idf_monitor.py -p /dev/cu.usbserial-0001 -b 115200 --toolchain-prefix xtensa-esp32-elf- --target esp32 --revision 0 /Users/tanwat/MICROCONTROLLER/091-Week-11-Microcontroller-applications/091-Week-11-Microcontroller-applications/LAB11-01/build/LAB11-01.elf /Users/tanwat/MICROCONTROLLER/091-Week-11-Microcontroller-applications/091-Week-11-Microcontroller-applications/LAB11-01/build/bootloader/bootloader.elf -m '/Users/tanwat/.espressif/python_env/idf6.0_py3.13_env/bin/python' '/Users/tanwat/esp-idf/tools/idf.py'
[0;33m--- esp-idf-monitor 1.8.0 on /dev/cu.usbserial-0001 115200[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H[0m
[0m--- 0x40080400: [0;33m_invalid_pc_placeholder[0m[0m at [0;32m/Users/tanwat/esp-idf/components/xtensa/xtensa_vectors.S[0m[0m:[1;31m2235[0m
[0m--- 0x40080638: [0;33m_stext[0m[0m at [0;32m??[0m[0m:[1;31m?[0m
[0;33m--- Warning: Checksum mismatch between flashed and built applications. Checksum of built application is 3201aef1d042f04ec7a4ef534e281199ffd015e79a38537529f1d7e3cd42488f[0m
[1;31m--- Error: read failed: [Errno 6] Device not configured[0m
[0;33m--- Waiting for the device to reconnect[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m.[0m[0;33m[0m
[0m
